version: "3"
services:
  web:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    #If the app is not detecting changes
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
